jobs:
 - name: hourly
   schedule: 0 * * * *
   steps:
     - name: Load dependencies
       command: dbt deps
     - name: Run models
       command: dbt run
     - name: Test models
       command: dbt test
